### ISSUE TITLE
A new learner  of openrisc

### ISSUE THREAD

**Issue by CaptainPrice92** [openrisc/or1200#1]
I am a new learner of openrisc , and I got completely no idea where can I get the source codes of or1200. I want to use this on my zedboard , but I stil have no idea how can I start this. Are there any people who have experiences about this , I really need some help .

**Comment by olofk** [comment]
This repository contains the source code for or1200. If you want to run a whole SoC on a FPGA board however, you need a lot more than just the or1200 source code.

Closing this
